import * as vscode from 'vscode';
import { exec as execCallback } from 'child_process';
import { promisify } from 'util';

const exec = promisify(execCallback);

interface CommandResult {
	stdout: string;
	stderr: string;
}

async function run(command: string, cwd: string): Promise<CommandResult> {
	try {
		const { stdout, stderr } = await exec(command, { cwd });
		return { stdout: stdout.trim(), stderr: stderr.trim() };
	} catch (error: any) {
		// exec rejects on non-zero exit; surface stderr/stdout for diagnosis.
		const stderr = error?.stderr?.trim() || error?.message || String(error);
		throw new Error(`"${command}" failed: ${stderr}`);
	}
}

function slugify(text: string): string {
	return text
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '')
		.slice(0, 50) || 'update';
}

/**
 * Full flow: verify repo + gh are usable -> collect branch/commit/PR details
 * from the user -> branch, commit, push -> create PR via `gh pr create`.
 * Every git/gh call runs with the workspace root as cwd.
 */
export async function runRaisePR(): Promise<void> {

	const workspaceFolder = vscode.workspace.workspaceFolders?.[0];

	if (!workspaceFolder) {
		vscode.window.showWarningMessage('Local Coding Agent: open a workspace folder first.');
		return;
	}

	const cwd = workspaceFolder.uri.fsPath;

	try {
		await run('git rev-parse --is-inside-work-tree', cwd);
	} catch {
		vscode.window.showErrorMessage('Local Coding Agent: this workspace is not a git repository.');
		return;
	}

	try {
		await run('gh --version', cwd);
	} catch {
		vscode.window.showErrorMessage(
			'Local Coding Agent: the gh CLI was not found on PATH. Install it and run `gh auth login` first.'
		);
		return;
	}

	const status = await run('git status --porcelain', cwd);
	if (!status.stdout) {
		vscode.window.showInformationMessage('Local Coding Agent: no changes to commit — working tree is clean.');
		return;
	}

	const commitMessage = await vscode.window.showInputBox({
		prompt: 'Commit message',
		placeHolder: 'Optimize FooService and add JUnit coverage',
	});
	if (!commitMessage) {
		return;
	}

	const defaultBranch = `agent/${slugify(commitMessage)}`;
	const branchName = await vscode.window.showInputBox({
		prompt: 'Branch name for this change',
		value: defaultBranch,
	});
	if (!branchName) {
		return;
	}

	const prTitle = await vscode.window.showInputBox({
		prompt: 'Pull request title',
		value: commitMessage,
	});
	if (!prTitle) {
		return;
	}

	const prBody = await vscode.window.showInputBox({
		prompt: 'Pull request description (optional)',
		placeHolder: 'Generated by Local Coding Agent',
	}) ?? 'Generated by Local Coding Agent.';

	try {
		await vscode.window.withProgress(
			{
				location: vscode.ProgressLocation.Notification,
				title: 'Local Coding Agent: raising PR...',
				cancellable: false,
			},
			async (progress) => {

				progress.report({ message: `creating branch ${branchName}` });
				// -B creates or resets the branch; safe to re-run if it already exists locally.
				await run(`git checkout -B ${branchName}`, cwd);

				progress.report({ message: 'staging changes' });
				await run('git add -A', cwd);

				progress.report({ message: 'committing' });
				const escapedMessage = commitMessage.replace(/"/g, '\\"');
				await run(`git commit -m "${escapedMessage}"`, cwd);

				progress.report({ message: 'pushing branch' });
				await run(`git push -u origin ${branchName}`, cwd);

				progress.report({ message: 'creating pull request' });
				const escapedTitle = prTitle.replace(/"/g, '\\"');
				const escapedBody = prBody.replace(/"/g, '\\"');
				const prResult = await run(
					`gh pr create --title "${escapedTitle}" --body "${escapedBody}"`,
					cwd
				);

				const urlMatch = prResult.stdout.match(/https:\/\/github\.com\/\S+/);
				const prUrl = urlMatch?.[0];

				if (prUrl) {
					const choice = await vscode.window.showInformationMessage(
						`Local Coding Agent: pull request created.`,
						'Open PR'
					);
					if (choice === 'Open PR') {
						vscode.env.openExternal(vscode.Uri.parse(prUrl));
					}
				} else {
					vscode.window.showInformationMessage(
						`Local Coding Agent: PR command completed.\n${prResult.stdout}`
					);
				}
			}
		);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		vscode.window.showErrorMessage(`Local Coding Agent: ${message}`);
	}
}